[workspace]
members = [
    "tests",
    "werk-cli", "werk-depfile",
    "werk-eval",
    "werk-fs",
    "werk-parser",
    "werk-planner",
    "werk-runner",
    "werk-util",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
rust-version = "1.85"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
ahash = "0.8.11"
annotate-snippets = "0.12.10"
anstream = "0.6.18"
bitflags = "2.8.0"
event-listener = "5.4.1"
futures = "0.3.31"
globset = "0.4.15"
ignore = "0.4.23"
indexmap = { version = "2.6.0", features = ["serde"] }
literator = "0.4.0"
parking_lot = "0.12.3"
pin-project-lite = "0.2.17"
regex = "1.11.1"
regex-syntax = "0.8.5"
rustc-stable-hash = "0.1.0"
serde = { version = "1.0.215", features = ["derive"] }
smol = "2.0.2"
stringleton = { version = "0.2.1", features = ["serde"] }
thiserror = "2.0"
tinyvec = { version =  "1.11.0", features = ["alloc"] }
toml_edit = "0.23.9"
tracing = "0.1.40"
werk-depfile.path = "werk-depfile"
werk-eval.path = "werk-eval"
werk-fs.path = "werk-fs"
werk-parser.path = "werk-parser"
werk-planner.path = "werk-planner"
werk-runner.path = "werk-runner"
werk-util.path = "werk-util"
which = "8.0.0"
winnow = "1.0.2"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_panics_doc = "allow"
missing_errors_doc = "allow"
inline_always = "allow"
similar_names = "allow"

[profile.release]
codegen-units = 1
lto = true
