use std::collections::BTreeMap;

use stringleton::Symbol;
use werk_eval::Io;
use werk_fs::Absolute;
use werk_util::{IoError, hash128::Hash128};

pub const WERK_CACHE_FILENAME: &str = ".werk-cache";

/// The contents of `.werk-cache`.
#[derive(Debug, Default, serde::Serialize, serde::Deserialize)]
pub struct WerkCache {
    /// Per-build-target caches.
    #[serde(default)]
    pub build: BTreeMap<Absolute<werk_fs::PathBuf>, TargetOutdatednessCache>,
}

impl WerkCache {
    pub fn read(io: &dyn Io, output_dir: &Absolute<std::path::Path>) -> WerkCache {
        let werk_cache_path = output_dir.join(WERK_CACHE_FILENAME).unwrap();
        tracing::debug!("trying to read .werk-cache: {}", werk_cache_path.display());
        let data = match io.read_file(&werk_cache_path) {
            Ok(data) => data,
            Err(err) => {
                if err.error.kind() != std::io::ErrorKind::NotFound {
                    tracing::error!("Failed to read workspace cache, even though it exists: {err}");
                }
                tracing::debug!(".werk-cache does not exist");
                return WerkCache::default();
            }
        };

        if data.is_empty() {
            tracing::debug!(".werk-cache is empty");
            return WerkCache::default();
        }

        match toml_edit::de::from_slice(&data) {
            Ok(cache) => {
                tracing::trace!(".werk-cache contents: {cache:#?}");
                cache
            }
            Err(err) => {
                tracing::error!("Failed to parse workspace cache: {err}");
                WerkCache::default()
            }
        }
    }

    pub fn write(
        &self,
        io: &dyn Io,
        output_dir: &Absolute<std::path::Path>,
    ) -> Result<(), IoError> {
        fn make_table(item: &mut toml_edit::Item) -> Option<&mut toml_edit::Table> {
            match std::mem::take(item).into_table() {
                Ok(table) => {
                    *item = toml_edit::Item::Table(table);
                    if let toml_edit::Item::Table(table) = item {
                        Some(table)
                    } else {
                        unreachable!()
                    }
                }
                Err(not_table) => {
                    *item = not_table;
                    None
                }
            }
        }

        let mut doc = match toml_edit::ser::to_document(self) {
            Ok(data) => data,
            Err(err) => {
                tracing::error!("Serialization error writing .werk-cache: {err}");
                panic!("Serialization error writing .werk-cache: {err}");
            }
        };

        if let Some(build) = doc.get_mut("build") {
            let build = make_table(build).expect("build is not a table");
            build.set_implicit(true);
            for (_target, target_info) in build.iter_mut() {
                make_table(target_info);
            }
        }

        let toml = format!("# Generated by werk. It can be safely deleted.\n\n{doc}");

        let path = output_dir.join(WERK_CACHE_FILENAME).unwrap();
        tracing::debug!("writing .werk-cache to {}", path.display());

        if let Err(err) = io.create_parent_dirs(&path) {
            tracing::error!(
                "Error creating parent directory for .werk-cache '{}': {err}",
                output_dir.display()
            );
            return Err(err);
        }

        match io.write_file(&path, toml.as_bytes()) {
            Ok(()) => Ok(()),
            Err(err) => {
                tracing::error!("Error writing .werk-cache: {err}");
                Err(err)
            }
        }
    }
}

/// Per-target cache of used outdatedness information.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct TargetOutdatednessCache {
    /// Hash of the recipe AST.
    pub recipe_hash: Hash128,
    /// Hash of used glob patterns.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub glob: BTreeMap<Symbol, Hash128>,
    /// Hash of resolved binary paths.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub which: BTreeMap<Symbol, Hash128>,
    /// Hash of environment variables.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub env: BTreeMap<Symbol, Hash128>,
    /// Hash of the definitions (AST expressions) of global variables used.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub global: BTreeMap<Symbol, Hash128>,
    /// Hash of `define` variables.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub define: BTreeMap<Symbol, Hash128>,
}

impl TargetOutdatednessCache {
    #[inline]
    pub fn is_recipe_outdated(&self, new_hash: Hash128) -> bool {
        self.recipe_hash != new_hash
    }

    #[inline]
    pub fn is_glob_outdated(&self, glob: Symbol, new_hash: Hash128) -> bool {
        self.glob
            .get(&glob)
            .is_some_and(|old_hash| *old_hash != new_hash)
    }

    #[inline]
    pub fn is_which_outdated(&self, which: Symbol, new_hash: Hash128) -> bool {
        self.which
            .get(&which)
            .is_some_and(|old_hash| *old_hash != new_hash)
    }

    #[inline]
    pub fn is_env_outdated(&self, env: Symbol, new_hash: Hash128) -> bool {
        self.env
            .get(&env)
            .is_some_and(|old_hash| *old_hash != new_hash)
    }

    #[inline]
    pub fn is_define_outdated(&self, define: Symbol, new_hash: Hash128) -> bool {
        self.define
            .get(&define)
            .is_none_or(|old_hash| *old_hash != new_hash)
    }

    #[inline]
    pub fn is_global_outdated(&self, var: Symbol, new_hash: Hash128) -> bool {
        self.global
            .get(&var)
            .is_none_or(|old_hash| *old_hash != new_hash)
    }
}
