[package]
name = "werk-runner"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
ahash = "0.8.11"
annotate-snippets.workspace = true
anyhow = "1.0.93"
bitflags.workspace = true
futures.workspace = true
globset = "0.4.15"
ignore = "0.4.23"
indexmap.workspace = true
memchr = "2.7.4"
parking_lot.workspace = true
pin-project-lite = "0.2.16"
regex-syntax.workspace = true
regex.workspace = true
rustc-stable-hash.workspace = true
serde.workspace = true
smol.workspace = true
stringleton.workspace = true
thiserror.workspace = true
toml_edit = { workspace = true, features = ["serde"] }
tracing.workspace = true
walkdir = "2.5.0"
werk-depfile.workspace = true
werk-eval.workspace = true
werk-fs.workspace = true
werk-parser.workspace = true
werk-planner.workspace = true
werk-util.workspace = true
which = "8.0.0"
winnow.workspace = true

[lints]
workspace = true
