[package]
name = "werk-util"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
ahash.workspace = true
annotate-snippets.workspace = true
event-listener.workspace = true
indexmap.workspace = true
parking_lot.workspace = true
pin-project-lite.workspace = true
rustc-stable-hash.workspace = true
serde.workspace = true
unicode-segmentation = "1.13.2"

[lints]
workspace = true
