use futures::channel::oneshot;
use werk_eval::{BuildRecipeMatch, RecipeMatch, TaskId};
use werk_fs::Absolute;

use crate::Error;

use super::BuildStatus;

pub enum TaskStatus {
    Built(Result<BuildStatus, Error>),
    Pending(Vec<oneshot::Sender<Result<BuildStatus, Error>>>),
}

pub enum TaskSpec<'a> {
    Recipe(RecipeMatch<'a>),
    CheckExists(Absolute<werk_fs::PathBuf>),
    /// Check if the file exists, but don't emit an error if it doesn't. This
    /// applies to dependencies discovered through depfiles, where the depfile
    /// may be outdated (from a previous build).
    ///
    /// If the file does not exist, the task will be considered outdated.
    CheckExistsRelaxed(Absolute<werk_fs::PathBuf>),
}

impl TaskSpec<'_> {
    #[must_use]
    pub fn to_task_id(&self) -> TaskId {
        match self {
            TaskSpec::Recipe(RecipeMatch::Build(build_recipe_match)) => {
                TaskId::build(build_recipe_match.target_file.clone())
            }
            TaskSpec::Recipe(RecipeMatch::Task(task_recipe_match)) => {
                TaskId::command(task_recipe_match.name)
            }
            TaskSpec::CheckExists(path_buf) | TaskSpec::CheckExistsRelaxed(path_buf) => {
                TaskId::build(path_buf.clone().into_boxed_path())
            }
        }
    }
}

pub enum DepfileSpec<'a> {
    /// The depfile is explicitly generated by a recipe.
    Recipe(BuildRecipeMatch<'a>),
    /// The depfile is implicitly generated by the associated command recipe.
    ImplicitlyGenerated(Absolute<werk_fs::PathBuf>),
}
