[package]
name = "werk-planner"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
werk-parser.workspace = true
werk-util.workspace = true
werk-fs.workspace = true
stringleton.workspace = true

[lib]
path = "lib.rs"

[lints]
workspace = true
